source 'https://rubygems.org' do

  gem 'rails', '4.2.5'

  gem 'haml-rails', '~> 0.9'

  gem 'sass-rails', '~> 5.0'

  gem 'bootstrap', '~> 4.0.0.alpha3'

  gem 'uglifier', '>= 1.3.0'

  gem 'jquery-rails', '~> 4.0.5'

  gem 'jquery-ui-rails', '~> 5.0.4'

  gem 'turbolinks', '~> 2.5.3'

  gem 'jbuilder', '~> 2.0'

  gem 'font-awesome-sass', '~> 4.5.0'

  gem 'faraday', '~> 0.9.2'

  gem 'bourbon', '~> 4.2.6'

  group :development do

    gem 'spring', '~> 1.6.1'

  end

end

source 'https://rails-assets.org' do

  gem 'rails-assets-tether', '>= 1.1.0'

end