source 'https://rubygems.org'

gem 'rails', '4.2.5'

gem 'haml-rails', '~> 0.9'

gem 'sass-rails', '~> 5.0'

gem 'bootstrap', '~> 4.0.0.alpha3'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails', '~> 4.0.5'

gem 'jquery-ui-rails', '~> 5.0.4'

gem 'react-rails', '~> 1.5.0'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'font-awesome-sass', '~> 4.5.0'

gem 'faraday', '~> 0.9.2'

# Use Unicorn as the app server
# gem 'unicorn'

group :development, :test do
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

source 'https://rails-assets.org' do

  gem 'rails-assets-tether', '>= 1.1.0'
end